using System.Runtime.InteropServices;

namespace AutoKeyNet.WindowsHooks.WindowsStruct;

/// <summary>
///     Contains information about a simulated message generated by an input device other than a keyboard or mouse.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct HardwareInput
{
    /// <summary>
    ///     The message generated by the input device. This member can be one of the following values:
    ///     <see cref="InputType.INPUT_MOUSE" /> or <see cref="InputType.INPUT_HARDWARE" />.
    /// </summary>
    public uint Message;

    /// <summary>
    ///     The low-order word of the lParam parameter for <see cref="Message" />.
    /// </summary>
    public ushort ParamL;

    /// <summary>
    ///     The high-order word of the lParam parameter for <see cref="Message" />.
    /// </summary>
    public ushort ParamH;
}